### ISSUE TITLE
Is it possible to view the training repo m4?

### ISSUE THREAD

**Issue by GCYYfun** [huggingface/m4-logs#2]
I saw a very detailed log of the training process in the repo, great share!
However, I see that the README mentions the training repository m4, but when I open it, the page says it doesn't exist.
I would like to know if it is possible to view the m4 training repository.
Thank you！

**Comment by VictorSanh** [comment]
Hi @GCYYfun 
thanks for the kind words!
There is no concrete timeline as of now to open the training code on our side.
